version: 2
jobs:
  build:
    working_directory: /go/src/github.com/hamakn/go_ddd_webapp
    docker:
      - image: mercari/appengine-go:1.8
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: go get -u golang.org/x/lint/golint
      - run: go get -u github.com/daisuzu/gsc
      - run: dep ensure -vendor-only
      - type: cache-save
        key: dep-cache-{{ checksum "Gopkg.lock" }}
        paths:
          - vendor
      - run: golint -set_exit_status ./config... && golint -set_exit_status ./src/...
      - run: RESULT=$(gofmt -d -s ./config/ ./src/) && echo "${RESULT}"; ! [ -n "${RESULT}" ]
      - run: go vet ./config/... ./src/...
      - run: gsc -tests=false ./config/... ./src/...
      - run: goapp test ./config/... ./src/...
